### ISSUE TITLE
Xtoken swap and pool 

### ISSUE THREAD

**Issue by satoshigrey** [syncswapxyz/SyncSwap-Testnet-Issue-Tracker#2]
X token doesn't match with other tokens to make swap or create pool deposit

**Comment by Gokturk67** [comment]
deposit and credit features
-Fill in the empty fields on the sides with an image (trademark or something else)
-% of my pools, balances, etc.
-how my cryptocurrency balance has changed in $ and %.
-article de discord hasan03#0117
