### ISSUE TITLE
always failed to remove 100% liquidity, but it is OK to remove 50%

### ISSUE THREAD

**Issue by joincc** [syncswapxyz/SyncSwap-Testnet-Issue-Tracker#3]
![image](https://user-images.githubusercontent.com/10822497/162595848-e7b15ff1-e69d-4182-bd5e-46b287b14490.png)

**Comment by syncswapxyz** [comment]
Thank you for your feedback. This was possibly caused by price volatility, and it's not a bug. However, we will add a human-readable error message for it.
